<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9NURHT7" name="com.auto.trans.TransV72ReqTest" tests="18" failures="3" timestamp="19 Aug 2016 10:02:40 GMT" time="78.935" errors="0">
  <testcase name="testTransReqWithHalfDay_Success" time="0.003" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithoutAutoOrder_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWith15Days_Success" time="0.011" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithAutoOrder_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithBugNo7671_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithCoupon_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithMaxRentTimeOrder_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithMoney_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWith7Days_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithBusyTimeLimit_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithEmptyToken_Failure" time="0.595" classname="com.auto.trans.TransV72ReqTest">
    <failure type="java.lang.AssertionError" message="expected [errorCode=200008] but found [errorCode=400001]">
      <![CDATA[java.lang.AssertionError: expected [errorCode=200008] but found [errorCode=400001]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.auto.http.HttpApi.execute(HttpApi.java:153)
	at com.auto.AbstractAutoAPITest.sendRequestWithExpectedError(AbstractAutoAPITest.java:70)
	at com.auto.AbstractAutoAPITest.testWithEmptyToken_Failure(AbstractAutoAPITest.java:128)
	at com.auto.trans.TransV72ReqTest.testTransReqWithEmptyToken_Failure(TransV72ReqTest.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- testTransReqWithEmptyToken_Failure -->
  <testcase name="testTransReqWithoutCoupon_Success" time="78.266" classname="com.auto.trans.TransV72ReqTest">
    <failure type="java.lang.AssertionError" message="resCode:500036		resMsg:租车时间和非空闲时间冲突。">
      <![CDATA[java.lang.AssertionError: resCode:500036		resMsg:租车时间和非空闲时间冲突。
	at org.testng.Assert.fail(Assert.java:94)
	at com.auto.http.HttpApi.execute(HttpApi.java:160)
	at com.auto.AbstractAutoAPITest.sendRequestAndGetResponse(AbstractAutoAPITest.java:49)
	at com.auto.trans.TransV72ReqTest.testTransReqWithoutCoupon_Success(TransV72ReqTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- testTransReqWithoutCoupon_Success -->
  <testcase name="testTransReqWithMulitOrder_Failure" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithTokenNull_Failure" time="0.021" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithFakeToken_Failure" time="0.026" classname="com.auto.trans.TransV72ReqTest">
    <failure type="java.lang.AssertionError" message="expected [errorCode=200008] but found [errorCode=400001]">
      <![CDATA[java.lang.AssertionError: expected [errorCode=200008] but found [errorCode=400001]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.auto.http.HttpApi.execute(HttpApi.java:153)
	at com.auto.AbstractAutoAPITest.sendRequestWithExpectedError(AbstractAutoAPITest.java:70)
	at com.auto.AbstractAutoAPITest.testWithFakeToken_Failure(AbstractAutoAPITest.java:138)
	at com.auto.trans.TransV72ReqTest.testTransReqWithFakeToken_Failure(TransV72ReqTest.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- testTransReqWithFakeToken_Failure -->
  <testcase name="testTransReqWith25Days_Success" time="0.002" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWith8Days_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
  <testcase name="testTransReqWithoutBusyTimeLimit_Success" time="0.001" classname="com.auto.trans.TransV72ReqTest"/>
</testsuite> <!-- com.auto.trans.TransV72ReqTest -->
